spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 50
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

acme:
  persistence:
    open-in-view: false
    ddl-auto: none
    time-zone: UTC
    jdbc-batch-size: 50
    order-inserts: true
    order-updates: true
    jpa:
      auditing-enabled: true
    tx:
      default-timeout-seconds: 30
